//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace main.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    //模型驗證，設定每一個屬性皆為必要
    public partial class Product
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public string CategoryId { get; set; }
        [Required]
        public string Price { get; set; }
        [Required]
        public string PublishDate { get; set; }
        [Required]
        public string Status { get; set; }
        [Required]
        public string DefaultImageId { get; set; }
        [Required]
        public string Quantity { get; set; }
    }
}
